blank_issues_enabled: false
contact_links:
  - name: wenamechainasama, unanse a pampu si llegan a leer esto
    url: https://discord.gg/sH4qnyeu7u
    about: también entren a mi youtube https://youtube.com/@BellevenHeaven
